//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Newsun.Common {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class CommConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static CommConfig defaultInstance = ((CommConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CommConfig())));
        
        public static CommConfig Default {
            get {
                return defaultInstance;
            }
        }
    }
}
